FROM demoregistry.dataman-inc.com/library/centos7-base:20160907193907
MAINTAINER pro zpang@dataman-inc.com

ENV NODE_EXPORTER_VERSION=0.14.0
ENV NODE_EXPORTER_PKG_NAME=node_exporter-${NODE_EXPORTER_VERSION}.linux-amd.tar.gz

https://github.com/prometheus/node_exporter/releases/download/v0.14.0/node_exporter-0.14.0.linux-amd64.tar.gz

RUN curl -o $NODE_EXPORTER_PKG_NAME  https://github.com/prometheus/node_exporter/releases/download/${NODE_EXPORTER_VERSION}/${NODE_EXPORTER_PKG_NAME} && \
	             tar xzvf $NODE_EXPORTER_PKG_NAME -d / && \
		     rm -Rf $NODE_EXPORTER_PKG_NAME
